// c:\Users\johnw\portfolio\src\lib\indexeddb\amazon-tools-db.ts
import Dexie, { type Table } from 'dexie';
import type {
  CsvColumnMapping,
  UserCsvMappingRecord,
} from '@/types/data-mapping';
import type { DashboardMetrics } from '@/app/amazon-seller-tools/page';
import type { CalculationEntry } from '@/app/amazon-seller-tools/acos-calculator';

const USER_CSV_MAPPINGS_STORE_NAME: string = 'userCsvMappings';

// Interface for records in the 'calculations' table (example from AcosCalculator)
export interface CalculationDBRecord {
  id?: number; // Auto-generated by IndexedDB
  calculationType: string;
  data: Omit<CalculationEntry, 'id'>; // The 'data' field stores the actual calculation details
  timestamp: Date; // To get the latest or for auditing
}

// New interface for storing the entire overview metrics array
export interface OverviewMetricsDBRecord {
  id?: number; // Auto-incrementing primary key, or use toolName as primary if unique
  toolName: string; // e.g., "overview-dashboard-data"
  metrics: DashboardMetrics[]; // The array of metrics
  timestamp: Date; // Timestamp of the last update
}

export class AmazonToolsDB extends Dexie {
  calculations!: Table<CalculationDBRecord>;
  userCsvMappings!: Table<UserCsvMappingRecord>;
  overviewMetricsData!: Table<OverviewMetricsDBRecord>;

  constructor() {
    super('AmazonToolsDB'); // Database name
    const userCsvMappingsIndex = '++id, toolName, timestamp';
    this.version(2).stores({
      calculations: '++id, calculationType, timestamp',
      userCsvMappings: userCsvMappingsIndex,
    });

    this.version(3).stores({
      calculations: '++id, calculationType, timestamp',
      userCsvMappings: userCsvMappingsIndex,
      overviewMetricsData: '++id, toolName, timestamp', // 'toolName' can be an index for querying
    });
  }
}

export const db = new AmazonToolsDB();
