// c:\Users\johnw\portfolio\src\lib\indexeddb\amazon-tools-db.ts
import Dexie, { type Table } from 'dexie';
import type {
  CsvColumnMapping,
  UserCsvMappingRecord,
} from '@/types/data-mapping';
import type { DashboardMetrics } from '@/lib/amazon-tools/types';
import type { CalculationData } from '@/lib/indexeddb-service';

const USER_CSV_MAPPINGS_STORE_NAME: string = 'userCsvMappings';

// Interface for records in the 'calculations' table (example from AcosCalculator)
export interface CalculationDBRecord {
  id?: number; // Auto-generated by IndexedDB
  calculationType: string;
  data: Omit<CalculationData, 'id'>; // The 'data' field stores the actual calculation details
  timestamp: Date; // To get the latest or for auditing
}

// New interface for storing the entire overview metrics array
export interface OverviewMetricsDBRecord {
  id?: number; // Auto-incrementing primary key, or use toolName as primary if unique
  toolName: string; // e.g., "overview-dashboard-data"
  metrics: DashboardMetrics[]; // The array of metrics
  timestamp: Date; // Timestamp of the last update
}

export interface KpiConfigDBRecord {
  id?: number;
  configName: string; // e.g., 'default-kpis' or a user-defined name
  selectedMetrics: string[];
  timestamp: Date;
}
// Schema definition constant for stores indexed by toolName and timestamp
const TOOL_NAME_TIMESTAMP_INDEX_SCHEMA = '++id, toolName, timestamp';

export class AmazonToolsDB extends Dexie {
  calculations!: Table<CalculationDBRecord>;
  userCsvMappings!: Table<UserCsvMappingRecord>;
  overviewMetricsData!: Table<OverviewMetricsDBRecord>;
  kpiConfigs!: Table<KpiConfigDBRecord>;

  constructor() {
    super('AmazonToolsDB'); // Database name
    // Use the new constant for relevant store schemas
    const userCsvMappingsStore = TOOL_NAME_TIMESTAMP_INDEX_SCHEMA;
    const calculationsStore = '++id, calculationType, timestamp';
    const overviewMetricsStore = TOOL_NAME_TIMESTAMP_INDEX_SCHEMA;
    const kpiConfigsStore = '++id, configName';

    this.version(2).stores({
      calculations: calculationsStore,
      userCsvMappings: userCsvMappingsStore,
    });
    this.version(3).stores({
      calculations: calculationsStore,
      userCsvMappings: userCsvMappingsStore,
      overviewMetricsData: overviewMetricsStore, // 'toolName' can be an index for querying
    });
    this.version(4).stores({
      calculations: calculationsStore,
      userCsvMappings: userCsvMappingsStore,
      overviewMetricsData: overviewMetricsStore,
      kpiConfigs: kpiConfigsStore, // 'configName' will be unique for KPI configs
    });
  }
}

export const db = new AmazonToolsDB();
