import React, { useState, useEffect } from 'react';
import { calculateAcos } from '@/lib/utils/amazon/calculations';
import { db } from '@/lib/indexeddb/amazon-tools-db';
import Button from '@/components/shared/Button';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';

interface CalculationEntry {
  id?: number;
  date: string;
  campaignName?: string;
  productIdentifier?: string;
  adSpend: number;
  adSales: number;
  acos: number;
  roas: number;
}

// Interface for the structure of entries in the IndexedDB 'calculations' table
interface CalculationDBRecord {
  id?: number; // Auto-generated by IndexedDB
  calculationType: string;
  // The 'data' field stores the actual calculation details, matching CalculationEntry (without its own id)
  data: Omit<CalculationEntry, 'id'>;
  timestamp: Date;
}

// Interface to represent the shape of records as TypeScript infers them
// from the Dexie query, especially if the 'data' field is initially 'unknown'.
interface DexieRawRecord {
  id?: number;
  calculationType: string;
  data: unknown; // The 'data' field as potentially unknown type from DB
  timestamp: Date;
}

const AcosCalculator = () => {
  const [adSpend, setAdSpend] = useState<number>(0);
  const [adSales, setAdSales] = useState<number>(0);
  const [acos, setAcos] = useState<number>(0);
  const [roas, setRoas] = useState<number>(0);
  const [targetAcos, setTargetAcos] = useState<number>(0);
  const [calculationHistory, setCalculationHistory] = useState<
    CalculationEntry[]
  >([]);
  const [campaignName, setCampaignName] = useState<string>('');
  const [productIdentifier, setProductIdentifier] = useState<string>('');

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = async () => {
    // Fetch raw data from IndexedDB. TypeScript indicates that the 'data' property
    // on these records might be 'unknown' initially.
    const rawHistoryFromDB: DexieRawRecord[] = await db.calculations
      .where('calculationType')
      .equals('acos')
      .reverse()
      .sortBy('timestamp');

    setCalculationHistory(
      rawHistoryFromDB
        .filter((record): record is CalculationDBRecord => {
          // This type guard validates that the record, and specifically its 'data' property,
          // conforms to the structure of CalculationDBRecord.
          // It ensures 'record.data' is an object and not null, making it compatible
          // with 'Omit<CalculationEntry, "id">'.
          return record && typeof record.data === 'object' && record.data !== null;
        })
        .map((validatedRecord: CalculationDBRecord): CalculationEntry => {
          // After the filter, validatedRecord is confirmed to be of type CalculationDBRecord.
          // Thus, validatedRecord.data is correctly typed as Omit<CalculationEntry, "id">.
          return {
            id: validatedRecord.id,
            ...validatedRecord.data, // Spread the properties from the nested 'data' object
          };
        }),
    );
  };

  const handleCalculate = () => {
    const calculatedAcos = calculateAcos(adSpend, adSales);
    setAcos(calculatedAcos);
    setRoas(adSales === 0 ? 0 : adSales / adSpend);
  };

  const handleSave = async () => {
    if (isNaN(acos) || acos === 0) {
      alert('Calculate ACoS first.');
      return;
    }

    const newEntry: CalculationEntry = {
      date: new Date().toISOString().slice(0, 10),
      campaignName: campaignName,
      productIdentifier: productIdentifier,
      adSpend: adSpend,
      adSales: adSales,
      acos: acos,
      roas: roas,
    };

    await db.calculations.add({
      calculationType: 'acos',
      data: newEntry,
      timestamp: new Date(),
    });
    await loadHistory();
    setCampaignName('');
    setProductIdentifier('');
  };

  const acosStatus =
    targetAcos > 0 && acos > targetAcos
      ? 'text-red-500'
      : targetAcos > 0 && acos <= targetAcos
        ? 'text-green-500'
        : '';

  const chartData = calculationHistory.map((entry) => ({
    date: entry.date,
    acos: entry.acos,
  }));

  return (
    <div className="p-4">
      <h2 className="text-2xl font-bold mb-4">ACoS Calculator</h2>

      <div className="mb-4">
        <label
          htmlFor="adSpend"
          className="block text-gray-700 text-sm font-bold mb-2"
        >
          Ad Spend
        </label>
        <input
          type="number"
          id="adSpend"
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          value={adSpend}
          onChange={(e) => setAdSpend(parseFloat(e.target.value))}
        />
      </div>

      <div className="mb-4">
        <label
          htmlFor="adSales"
          className="block text-gray-700 text-sm font-bold mb-2"
        >
          Ad Sales
        </label>
        <input
          type="number"
          id="adSales"
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          value={adSales}
          onChange={(e) => setAdSales(parseFloat(e.target.value))}
        />
      </div>

      <Button onClick={handleCalculate}>Calculate ACoS</Button>

      {acos > 0 && (
        <div className="mt-4">
          <p>
            ACoS: <span className={acosStatus}>{acos.toFixed(2)}%</span>
          </p>
          <p>Break-Even RoAS: {roas.toFixed(2)}</p>
        </div>
      )}

      <div className="mb-4">
        <label
          htmlFor="targetAcos"
          className="block text-gray-700 text-sm font-bold mb-2"
        >
          Target ACoS (%)
        </label>
        <input
          type="number"
          id="targetAcos"
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          value={targetAcos}
          onChange={(e) => setTargetAcos(parseFloat(e.target.value))}
        />
      </div>

      <div className="mb-4">
        <label
          htmlFor="campaignName"
          className="block text-gray-700 text-sm font-bold mb-2"
        >
          Campaign Name (Optional)
        </label>
        <input
          type="text"
          id="campaignName"
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          value={campaignName}
          onChange={(e) => setCampaignName(e.target.value)}
        />
      </div>

      <div className="mb-4">
        <label
          htmlFor="productIdentifier"
          className="block text-gray-700 text-sm font-bold mb-2"
        >
          Product Identifier (Optional)
        </label>
        <input
          type="text"
          id="productIdentifier"
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          value={productIdentifier}
          onChange={(e) => setProductIdentifier(e.target.value)}
        />
      </div>

      <Button onClick={handleSave}>Save Calculation</Button>

      {calculationHistory.length > 0 && (
        <div className="mt-4">
          <h3 className="text-lg font-bold mb-2">Calculation History</h3>
          <table className="table-auto w-full">
            <thead>
              <tr>
                <th className="px-4 py-2">Date</th>
                <th className="px-4 py-2">Campaign</th>
                <th className="px-4 py-2">Product</th>
                <th className="px-4 py-2">Ad Spend</th>
                <th className="px-4 py-2">Ad Sales</th>
                <th className="px-4 py-2">ACoS</th>
                <th className="px-4 py-2">RoAS</th>
              </tr>
            </thead>
            <tbody>
              {calculationHistory.map((entry) => (
                <tr key={entry.id}>
                  <td className="border px-4 py-2">{entry.date}</td>
                  <td className="border px-4 py-2">{entry.campaignName}</td>
                  <td className="border px-4 py-2">
                    {entry.productIdentifier}
                  </td>
                  <td className="border px-4 py-2">
                    {entry.adSpend.toFixed(2)}
                  </td>
                  <td className="border px-4 py-2">
                    {entry.adSales.toFixed(2)}
                  </td>
                  <td className="border px-4 py-2">{entry.acos.toFixed(2)}%</td>
                  <td className="border px-4 py-2">{entry.roas.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {chartData.length > 0 && (
        <div className="mt-4" style={{ width: '100%', height: 300 }}>
          <ResponsiveContainer>
            <LineChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="date" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Line
                type="monotone"
                dataKey="acos"
                stroke="#8884d8"
                activeDot={{ r: 8 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </div>
      )}
    </div>
  );
};

export default AcosCalculator;
