/**
 * Defines the structure for a Category within the CRM.
 * Categories help organize contacts.
 */
export interface Category {
  id: string; // Unique identifier for the category.
  name: string; // The name of the category (e.g., "Lead", "Customer", "Partner").
}

/**
 * Defines the structure for a Contact (Customer) within the CRM.
 * Represents an individual or organization managed in the system.
 */
export interface Contact {
  id: string; // Unique identifier for the contact, typically autogenerated.
  name: string; // Required: The full name of the contact.
  email?: string; // Optional: The contact's email address.
  phone?: string; // Optional: The contact's phone number.
  company?: string; // Optional: The company the contact is associated with.
  notes?: string; // Optional: General notes or remarks about the contact.
  category?: string; // Optional: The ID of the category this contact belongs to.
  createdAt?: number; // Optional: Timestamp (milliseconds since epoch) when the contact was created.
  updatedAt?: number; // Optional: Timestamp (milliseconds since epoch) when the contact was last updated.
  address?: string; // Optional: The physical address of the contact.
  communicationLogs?: CommunicationLog[]; // Optional: An array of communication log entries associated with this contact.
}

/**
 * Defines the structure for a Communication Log entry.
 * Records interactions with a specific customer.
 */
export interface CommunicationLog {
  id: string; // Unique identifier for the communication log entry.
  customerId: string; // Required: The ID of the customer this communication log is associated with.
  type: 'Call' | 'Email' | 'Meeting' | 'Other'; // Required: The type of communication.
  date: number; // Required: Timestamp (milliseconds since epoch) of when the communication occurred.
  subject?: string; // Optional: A brief subject or title for the communication.
  notes: string; // Required: Detailed notes about the communication.
}
