/**
 * Defines the structure for a Category within the CRM.
 * Categories help organize contacts.
 */
export interface Category {
  id: string; // Unique identifier for the category.
  name: string; // The name of the category (e.g., "Lead", "Customer", "Partner").
}

/**
 * Defines the structure for a Contact (Customer) within the CRM.
 * Represents an individual or organization managed in the system.
 */
export interface Contact {
  id: string; // Unique identifier for the contact, typically autogenerated.
  name: string; // Required: The full name of the contact.
  email?: string; // Optional: The contact's email address.
  phone?: string; // Optional: The contact's phone number.
  company?: string; // Optional: The company the contact is associated with.
  notes?: string; // Optional: General notes or remarks about the contact.
  category?: string; // Optional: The ID of the category this contact belongs to.
  createdAt?: number; // Optional: Timestamp (milliseconds since epoch) when the contact was created.
  updatedAt?: number; // Optional: Timestamp (milliseconds since epoch) when the contact was last updated.
  lastContacted?: number; // Optional: Timestamp (milliseconds since epoch) of the last communication.
  salesStage?: SalesStage | null; // Optional: The current sales stage of the contact, can be null.
  address?: string; // Optional: The physical address of the contact.
  communicationLogs?: CommunicationLog[]; // Optional: An array of communication log entries associated with this contact.
  highlightedName?: string; // Optional: Highlighted name for search results.
  // Add a new field for the last activity date, useful for CRM dashboards
  lastActivity?: number; // Timestamp of last interaction
  salesOpportunities?: SalesOpportunity[]; // Array of sales opportunities associated with this contact
  leadScore?: number; // Optional: The calculated lead score for the contact.
  leadScoreCategory?: 'Hot' | 'Warm' | 'Cold'; // Optional: Categorization of the lead score.
  tags?: string[]; // Optional: Tags for the contact.
  synced?: number; // New property to track sync status (0 for unsynced, 1 for synced)
}

import { SalesOpportunity, SalesStage } from './types/sales';
export type { SalesOpportunity, SalesStage }; // Re-export SalesOpportunity and SalesStage as types

export type CommunicationType = 'call' | 'email' | 'meeting' | 'chat';

/**
 * Defines the possible sales stages for the Contact.
 */
export const SALES_STAGES = [
  'Lead',
  'Prospect',
  'Qualified',
  'Proposal',
  'Negotiation',
  'Closed Won',
  'Closed Lost',
] as const satisfies readonly string[];

/**
 * Defines the structure for a Communication Log entry.
 * Records interactions with a specific customer.
 */
export interface CommunicationLog {
  id: string; // Unique identifier for the communication log entry.
  customerId: string; // Required: The ID of the customer this communication log is associated with.
  type: 'email' | 'chat' | 'call' | 'meeting'; // Required: The type of communication.
  date: number; // Required: Timestamp (milliseconds since epoch) of when the communication occurred.
  subject?: string; // Optional: A brief subject or title for the communication.
  body?: string; // Optional: The full body of the communication.
  direction?: 'inbound' | 'outbound'; // Optional: The direction of the communication.
  notes: string; // Required: Detailed notes about the communication.
  synced?: number; // New property to track sync status (0 for unsynced, 1 for synced)
}

/**
 * Defines the structure for an Email Template.
 */
export interface EmailTemplate {
  id: string; // Unique identifier for the email template.
  name: string; // The name of the email template.
  subject: string; // The subject line of the email.
  body: string; // The body content of the email, can include rich text.
  synced?: number; // New property to track sync status (0 for unsynced, 1 for synced)
}

/**
 * Defines the possible types of customer activities.
 */
export type ActivityType =
  | 'email_open'
  | 'website_visit'
  | 'form_submission'
  | 'support_ticket_update'
  | 'product_usage'
  | 'customer_created'
  | 'customer_updated'
  | 'customer_deleted' // Added for customer deletion
  | 'communication_logged'
  | 'communication_updated'
  | 'communication_deleted'
  | 'sales_opportunity_created' // Added for sales opportunity creation
  | 'sales_opportunity_updated' // Added for sales opportunity update
  | 'sales_opportunity_deleted'; // Added for sales opportunity deletion

/**
 * Defines the structure for an Activity Log entry.
 * Records various interactions and events related to a customer.
 */
export interface ActivityLog {
  id: string; // Unique identifier for the activity log entry.
  contactId: string; // Required: The ID of the contact this activity log is associated with.
  type: ActivityType; // Required: The type of activity (e.g., 'email_open', 'website_visit').
  description: string; // Required: A detailed description of the activity.
  timestamp: number; // Required: Timestamp (milliseconds since epoch) when the activity occurred.
  synced?: number; // New property to track sync status (0 for unsynced, 1 for synced)
}
