export interface Category {
  id: string;
  name: string;
}

export interface Contact {
  id?: string; // autogenerated, unique identifier
  name: string; // required
  email?: string;
  phone?: string;
  company?: string;
  notes?: string;
  category?: string; // New: Category for the contact
  creationTimestamp?: number; // milliseconds since epoch
  updateTimestamp?: number; // milliseconds since epoch
  address?: string;
  communicationLogs?: CommunicationLog[]; // New: Array of communication logs for the contact/customer
}

export interface CommunicationLog {
  id?: string; // Unique ID for the log entry
  customerId: string; // ID of the customer this communication relates to
  type: 'Call' | 'Email' | 'Meeting' | 'Other'; // Type of communication
  date: number; // Timestamp of the communication (e.g., milliseconds since epoch)
  subject?: string; // Subject of the communication
  notes: string; // Detailed notes about the communication
}
