import {
  GoogleGenerativeAI,
  GenerativeModel,
  GenerationConfig,
} from '@google/generative-ai';
import { initGeminiAI, AI_MODELS } from '@/lib/ai-config';

let geminiClient: GoogleGenerativeAI | null = null;
let generativeModel: GenerativeModel | null = null;

/**
 * Initializes and returns the Gemini API client.
 * Ensures the client is only initialized once.
 * @returns An initialized GoogleGenerativeAI client.
 */
export const getGeminiClient = (): GoogleGenerativeAI => {
  if (!geminiClient) {
    geminiClient = initGeminiAI();
  }
  return geminiClient;
};

/**
 * Initializes and returns the GenerativeModel for AI-driven recommendations.
 * Ensures the model is only initialized once with the default Gemini configuration.
 * @returns An initialized GenerativeModel.
 */
const getGenerativeModel = (): GenerativeModel => {
  if (!generativeModel) {
    const genAI = getGeminiClient();
    generativeModel = genAI.getGenerativeModel({
      model: AI_MODELS.gemini.default,
      generationConfig: AI_MODELS.gemini.config,
    });
  }
  return generativeModel;
};

/**
 * Makes an AI-driven recommendation based on the given prompt.
 * @param prompt The text prompt for the AI model.
 * @returns A promise that resolves to the generated text recommendation.
 * @throws {Error} If the API call fails or no text is generated.
 */
export const getAIDrivenRecommendation = async (
  prompt: string,
  generationConfig?: GenerationConfig, // Use GenerationConfig type
): Promise<string> => {
  try {
    const genAI = getGeminiClient();
    const model = genAI.getGenerativeModel({
      model: AI_MODELS.gemini.default,
      generationConfig: generationConfig || AI_MODELS.gemini.config, // Use provided config or default
    });
    const result = await model.generateContent(prompt);
    const response = result.response;
    const text = response.text();

    if (!text) {
      throw new Error('No text generated by the AI model.');
    }

    return text;
  } catch (error) {
    console.error('Error getting AI-driven recommendation:', error);
    throw new Error(
      `Failed to get AI-driven recommendation: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
};
