import { Button, CardContent, Input, Label } from '@/components/ui';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { CurrencySelector } from './CurrencySelector';
import React, { ChangeEvent, useCallback } from 'react';

interface ManualCalculationFormProps {
  selectedCurrency: {
    label: string;
    value: string;
    symbol: string;
  };
  setSelectedCurrency: (currency: {
    label: string;
    value: string;
    symbol: string;
  }) => void;
  manualCampaign: {
    campaign: string;
    adSpend: string;
    sales: string;
    impressions: string;
    clicks: string;
  };
  setManualCampaign: React.Dispatch<
    React.SetStateAction<{
      campaign: string;
      adSpend: string;
      sales: string;
      impressions: string;
      clicks: string;
    }>
  >;
  handleManualCalculate: () => Promise<void>;
  isManualInputValid: boolean;
  isLoading: boolean;
}

export function ManualCalculationForm({
  selectedCurrency,
  setSelectedCurrency,
  manualCampaign,
  setManualCampaign,
  handleManualCalculate,
  isManualInputValid,
  isLoading,
}: ManualCalculationFormProps) {
  const handleInputChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      const { name, value } = e.target;
      let sanitizedValue = value;
      if (name === 'adSpend' || name === 'sales') {
        sanitizedValue = value
          .replace(/[^\d.]/g, '')
          .replace(/(\..*)\./g, '$1')
          .replace(/^\./, '0.')
          .replace(/^0+(?=\d)/, '');
      } else if (name === 'campaign') {
        sanitizedValue = value.trimStart().slice(0, 100);
      }
      setManualCampaign(
        (prev: {
          campaign: string;
          adSpend: string;
          sales: string;
          impressions: string;
          clicks: string;
        }) => ({ ...prev, [name]: sanitizedValue }),
      );
    },
    [setManualCampaign],
  );

  return (
    <CardContent className="space-y-4">
      <CurrencySelector
        onCurrencyChange={(currency) => setSelectedCurrency(currency)}
      />
      <div>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger>
              <Label htmlFor="manual-campaign">Campaign Name*</Label>
            </TooltipTrigger>
            <TooltipContent>Enter the name of the campaign.</TooltipContent>
          </Tooltip>
        </TooltipProvider>
        <Input
          id="manual-campaign"
          name="campaign"
          value={manualCampaign.campaign}
          onChange={handleInputChange}
          placeholder="e.g., SP - Auto - Product A"
          disabled={isLoading}
        />
      </div>
      <div>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger>
              <Label htmlFor="manual-adSpend">Ad Spend ($)*</Label>
            </TooltipTrigger>
            <TooltipContent>
              Enter the amount spent on advertising for this campaign.
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
        <Input
          id="manual-adSpend"
          name="adSpend"
          type="text"
          inputMode="decimal"
          value={manualCampaign.adSpend}
          onChange={handleInputChange}
          placeholder="e.g., 150.75"
          disabled={isLoading}
        />
      </div>
      <div>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger>
              <Label htmlFor="manual-sales">Sales ($)*</Label>
            </TooltipTrigger>
            <TooltipContent>
              Enter the total sales generated by this campaign.
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
        <Input
          id="manual-sales"
          name="sales"
          type="text"
          inputMode="decimal"
          value={manualCampaign.sales}
          onChange={handleInputChange}
          placeholder="e.g., 600.50"
          disabled={isLoading}
        />
      </div>
      <div>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger>
              <Label htmlFor="manual-impressions">Impressions</Label>
            </TooltipTrigger>
            <TooltipContent>
              Enter the number of impressions for this campaign.
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
        <Input
          id="manual-impressions"
          name="impressions"
          type="text"
          inputMode="numeric"
          value={manualCampaign.impressions}
          onChange={handleInputChange}
          placeholder="e.g., 1000"
          disabled={isLoading}
        />
      </div>
      <div>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger>
              <Label htmlFor="manual-clicks">Clicks</Label>
            </TooltipTrigger>
            <TooltipContent>
              Enter the number of clicks for this campaign.
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
        <Input
          id="manual-clicks"
          name="clicks"
          type="text"
          inputMode="numeric"
          value={manualCampaign.clicks}
          onChange={handleInputChange}
          placeholder="e.g., 50"
          disabled={isLoading}
        />
      </div>
      <Button
        onClick={handleManualCalculate}
        disabled={!isManualInputValid || isLoading}
        className="w-full"
      >
        {isLoading ? 'Calculating...' : 'Calculate & Add'}
      </Button>
    </CardContent>
  );
}
